name: FrontendYML
'on': 
   pull_request:
    branches: 
      - main
   push:
    branches:
      - main

jobs:
  my-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: cd frontend && npm install

      - name: Run Tests
        run: cd frontend && npm test
